### ISSUE TITLE
Failures on CI-CD builds due to Blue Oak License on License Checks

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/design-authority-project#101]
## Request Summary: 

Several CI-CD builds are failing [License Scanner Checks using the Mojaloop "allowedList"](https://github.com/mojaloop/license-scanner-tool/blob/master/config.toml#L141) due to the introduction of a new License [Blue Oak v1.0.0](https://blueoakcouncil.org/2019/03/06/model.html) to Mojaloop's underlying dependencies.

Here is an example of the [SDK-Scheme-Adapter] --> https://app.circleci.com/pipelines/github/mojaloop/sdk-scheme-adapter/2670/workflows/8a0e2fb0-ff1a-49d3-affb-a3fcac5e7cb0/jobs/19235

It seems to be impacting several key dependencies, specifically [glob](https://github.com/mojaloop/central-ledger/blob/master/.ncurc.yaml#L9) and also [npm-check-updates](https://github.com/mojaloop/sdk-scheme-adapter/blob/master/package.json#L86). However, since this impacts a dependency like `glob`, it is more than likely that this issue will impact other dependencies going forward.

## **Request Details**:

We have a couple of options here:
1. Add the Blue Oak license to the [Mojaloop License Scanner "allowedList"](https://github.com/mojaloop/license-scanner-tool/blob/master/config.toml#L141), assuming the license is compatible with [Apache 2.0](https://www.apache.org/licenses/LICENSE-2.0) *(which I believe it is, as it is a permissive license)*
2. Downgrade dependencies to versions not impacted by this License issue <-- *Note: this approach is currently being taken as a workaround.* (Example of this is done in Yarn: https://github.com/mojaloop/sdk-scheme-adapter/commit/f7022afdc5629882007403aa05bdc557a24a0573), similarly this can be done on NPM using [Overrides](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides))
3. Find alternative dependencies that do not rely on the Blue Oak license <-- this may only be possible in some cases

---- 
- **Deadline:** TBC
- **Impact (Teams):** Possibly all contributing developers
- **Impact (Components):** Possibly all development contributions

<insert more information about your request>

**Artifacts**:
- [Blue Oak v1.0.0 License](https://blueoakcouncil.org/license/1.0.0)
- [Apache 2.0 License](https://www.apache.org/licenses/LICENSE-2.0)

**Dependencies**:
- n/a

### **Accountability**:
- **Owner:** <DA member responsible for issue>
- **Raised By:** @mdebarros 

## **Decision(s)**:

<fill in this section upon reaching a decision>

- **Approved By:** <Insert name>
  
### Details

- [ ] Actual decision made as a result of discussion

## **Follow-up**:

<fill in this section upon reaching a decision>
  
- [ ] Actions to implement the decisions

**Comment by elnyry-sam-k** [comment]
Thanks @mdebarros  and the DA team.

After consultation with legal experts (by Paula H) and Blue Oak team, we've been given the recommendation to go ahead with adding this license to the "allow / approved list". Thanks to Paula for helping resolve this quickly.

**Comment by mdebarros** [comment]
> Thanks @mdebarros and the DA team.
> 
> After consultation with legal experts (by Paula H) and Blue Oak team, we've been given the recommendation to go ahead with adding this license to the "allow / approved list". Thanks to Paula for helping resolve this quickly.

Great to hear! \:D/
