### ISSUE TITLE
Async Process Log file creation

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/design-authority-project#11]
## **Request**:
I would like to _refactor logger library to write to log files asynchronously (instead of writing to the console synchronously)_
to improve performance.

https://github.com/mojaloop/project/issues/574

**Artifacts**:
- [ ] Artifact to consider [@Contributor]

**Decision(s)**:
- [ ] Actual decision made as a result of discussion

## **Follow-up**:
- [ ] Alternative actions

**Dependencies**:
- [ ] If Applicable

## **Accountability**:
- Owner: 

## **Notes**:

**Comment by lewisdaly** [comment]
I think this has been covered in: https://github.com/mojaloop/project/issues/846

**Comment by MichaelJBRichards** [comment]
Completed already. Close it
