### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/design-authority-project#12]
## **Request**:
Identify scope and requirements

**Artifacts**:
- [ ] Artifact to consider [@Contributor]

**Decision(s)**:
- [ ] Actual decision made as a result of discussion

## **Follow-up**:
- [ ] Alternative actions

**Dependencies**:
- [ ] If Applicable

## **Accountability**:
- Owner: 

## **Notes**:

**Comment by MichaelJBRichards** [comment]
Too vague, close it
