### ISSUE TITLE
Introduce tool to support Defect Life Cycle Management

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/design-authority-project#14]
## **Request**:
We are going to start receiving defects from our clients which might translate into either mojaloop or Casablanca software dev defect. Our QA needs to get the communication going and managing these findings with different dev teams and reporting back to the client on the resolution status.
Is there any tool already Modusbox are using? I can imagine a simple scenario with a list of issues from cucumber linked back to Jira or Zenhub. But would worth the thinking how complex this management become within a multi-client environment.

**Artifacts**:
- [ ] Artifact to consider [@Contributor]

**Decision(s)**:
- [ ] Actual decision made as a result of discussion

## **Follow-up**:
- [ ] Alternative actions

**Dependencies**:
- [ ] If Applicable

## **Accountability**:
- Owner: 

## **Notes**:

**Comment by MichaelJBRichards** [comment]
We use GitHub, so this can be closed.
