### ISSUE TITLE
PRISM Discussion

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/design-authority-project#17]
## **Request**:

**Artifacts**:
- [ ] Artifact to consider [@Contributor]

**Decision(s)**:
- [ ] Actual decision made as a result of discussion

## **Follow-up**:
- [ ] Alternative actions

**Dependencies**:
- [ ] If Applicable

## **Accountability**:
- Owner: 

## **Notes**:

**Comment by mdebarros** [comment]
This will be addressed as part of the Performance work in PI8.

**Comment by MichaelJBRichards** [comment]
Will be addressed in vNext. Can be re-opened if required for vCurrent.
