### ISSUE TITLE
Request Duplicate Check

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/design-authority-project#29]
## **Request**:
Please verify the Request Duplicate Check Design - see associated Sequence Diagram

**Artifacts**:
- [x] https://docs.google.com/document/d/18zNB7ShWS5NiNdlAWffup5G5eOUtAwycTFyI3cni34c [@ggrg]

**Decision(s)**:
- [x] Actual decision made as a result of discussion --> Option 4

## **Follow-up**:
- options:
1. add completedRequest table
   a. <-- full accordance with the spec, insert ALL requests, which will support PUT operations
   b. <-- full accordance with the spec, insert only for invalid requests, which will support PUT operations
2. simplify API by removing GET response on POST/PUTs and just respond with a "DUPLICATE ERROR"
3. minimal validations up-front (pre-validations) prior to hash-check where we only store requests that "can be PROCESSED" by either the `prepare` or the `fulfil` handler and send the failed pre-validations to the audit log
4. support inserting invalid transfers with minimal info required (e.g. transferId, status,etc) - use existing db structures - https://github.com/mojaloop/design-authority/issues/9
  - prepare <-- will resolve the issues there
  - fulfil <-- does not resolve requests being sent from incorrect FSPs? (edited) 

**Dependencies**:
- [x] #780, #781

## **Accountability**:
- Owner: @ggrg

**Comment by NicoDuvenage** [comment]
The detail on the proposed solution after a meeting concluded on Jun 3, 2019, @ 19:00 SAST
To be presented by Georgi to DA on Jun 4 and discussions to be held over for the regular weekly DA meeting on Wednesday.
options:
1. add completedRequest table
   a. <-- full accordance with the spec, insert ALL requests, which will support PUT operations
   b. <-- full accordance with the spec, insert only for invalid requests, which will support PUT operations
2. simplify API by removing GET response on POST/PUTs and just respond with a "DUPLICATE ERROR"
3. minimal validations up-front (pre-validations) prior to hash-check where we only store requests that "can be PROCESSED" by either the `prepare` or the `fulfil` handler and send the failed pre-validations to the audit log (edited)

**Comment by NicoDuvenage** [comment]
At the DA meeting on Jun 5th, 2019, an additional option (4) was added and seemed to be the one worth investigating further. A meeting between interested parties will be arranged for Friday, Jun 7th after which this log will be updated with the recommended approach.

**Comment by mdebarros** [comment]
For *transfer fulfils* DA to consider:
 a. Aborting a prepared transfer for all cases when invalid fulfilment message is received (incl. bad fulfilment from payee, all payee errors, 3rd party attempting to commit etc.)
 b. Do not use provided header data (source/destination), but use stored data for callbacks instead

**Comment by mdebarros** [comment]
Next steps:
- Duplicate-check design to be updated to reflect the above decision.
- Story to update the Central-Ledger Prepare Handler to insert incomplete/invalid transfer records with all/as-much information as possible into the existing db structure.
- Story to re-factor the fulfilment handler to align the validations (specifically the duplication-check) in the same fashion as the prepare handler.

**Comment by elnyry** [comment]
Thanks Miguel, this looks good.
