### ISSUE TITLE
Hapi-openapi with Typescript

### ISSUE THREAD

**Issue by DonChangfoot** [mojaloop/design-authority-project#38]
## **Request**:
Discuss best way to use hapi-openapi with a typescript project.

**Artifacts**:
- [ ] example repo: https://github.com/DonChangfoot/Hapi-openapi-with-Typescript

**Decision(s)**:
- [ ] Actual decision made as a result of discussion

## **Follow-up**:
- [ ] Alternative actions

**Dependencies**:
- [ ] If Applicable

## **Accountability**:
- Owner:

**Comment by MichaelJBRichards** [comment]
Anything new should be TypeScript, should we update old services as well? What about HAPI? vNext uses Express. JB: what would we recommend now? PSB: we don't have to force a single one.  We make recommendations, but don't exclude the possibility of other object. PB: we could include pros and cons.
