### ISSUE TITLE
Discuss and Design an approach for supporting multiple versions of a Mojaloop Implementation

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/design-authority-project#39]
## **Request**:
There are some requests to have a design implemented where multiple versions of a mojaloop implementation can be catered for, both from an API as well as a Database perspective.

**Artifacts**:
- [ ] Current Draft Versioning Proposal PR: https://github.com/mojaloop/documentation/pull/182

You can view on the branch [here](https://github.com/mojaloop/documentation/blob/versioning/discussions/versioning_draft_proposal.md) to make it easier to read.

**Decision(s)**:
- [ ] Actual decision made as a result of discussion

## **Follow-up**:
- [ ] Alternative actions

**Dependencies**:
- [ ] If Applicable

## **Accountability**:
- Owner:

**Comment by NicoDuvenage** [comment]
See related OSS Story:
Determine Scope for Versioning Proposal #1199

**Comment by elnyry-sam-k** [comment]
[mojaloop_versioning_pi10.pdf](https://github.com/mojaloop/design-authority-project/files/11440482/mojaloop_versioning_pi10.pdf)

Design proposal made and shared during Mojaloop PI-10 event

**Comment by MichaelJBRichards** [comment]
A proposal has been made and accepted. We have a solution. JB: switch has to be aware of the API version, because there may be processing paths which are version-specific. What we should say is: the switch must be able to process messages which use any version in use in the implementation.
