### ISSUE TITLE
Merchant-Initiated Merchant Payment functionality on Mojaloop Simulator

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/design-authority-project#41]
## **Request**:
We are working on the reproduction of Merchant-Initiated Merchant Payment (page 63 here https://github.com/mojaloop/mojaloop-specification/blob/master/documents/supporting-documentation/API%20Definition%20v1.0.pdf) on our servers.

For this reason we setup K8S (helm v8.8.0), this FSP simulator https://github.com/mojaloop/simulator as Payer FSP and our own simulator as Payee FSP.

Based on our needs and Merchant payment flow, the Payer FSP, which is https://github.com/mojaloop/simulator, should do the next steps in order to behave like a real FSP provider:
   Initiate POST /quotes once received POST /transactionRequests
   Initiate POST /transfers once received PUT /quotes/{id}

Validate incoming messages for compliance with Mojaloop specification (https://github.com/mojaloop/mojaloop-specification/blob/master/Supporting%20Files/fspiop-rest-v1.0-OpenAPI-implementation.yaml) 

In order to receive these features, we downloaded Simulator's code from https://github.com/mojaloop/simulator and started adding necessary amendments there so that Simulator to behave like we need.

The question is how should we then push this code back to repo and who/how will review our request? Are we to follow the forking flow https://www.atlassian.com/git/tutorials/comparing-workflows/forking-workflow? or are there any other steps?

**Artifacts**:
- [ ] Artifact to consider [@Contributor]

**Decision(s)**:
- [ ] Actual decision made as a result of discussion

## **Follow-up**:
- [ ] Alternative actions

**Dependencies**:
- [ ] If Applicable

## **Accountability**:
- Owner: Anton Galaguz - agalaguz@justcoded.com

**Comment by adrianhopebailie** [comment]
👍 to adding the feature.

I suggest it be contributed as a PR against the repo which can be reviewed by the DA.

@NicoDuvenage and @elnyry as discussed on the call we should try and make it easier for contributors to suggest features and get a go ahead from the DA to start work on it.

Do all of the repos have code owners that could do this without needing the DA? That would mean contributors could simply log an issue on the repo and tag it as a proposal and the code owners can approve it or discuss it in the issue.

**Comment by godfreykutumela** [comment]
@NicoDuvenage Updated

**Comment by godfreykutumela** [comment]
This issue was deferred to a PR
