### ISSUE TITLE
Support for accented characters in data type "Name"

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/design-authority-project#42]
## **Request**:
In Section 7.2.4.1 of the API specification, the definition of the regular expression to parse a variable of the Name type states: "all Unicode32 characters are allowed". In fact, accented and non-Roman characters are rejected by the example regular expression given in Listing 14.

**Artifacts**:
- [ ] Artifact to consider [@Contributor]

**Decision(s)**:
- [ ] Actual decision made as a result of discussion

## **Follow-up**:
- [ ] Alternative actions

**Dependencies**:
- [ ] https://github.com/mojaloop/mojaloop-specification/issues/56

## **Accountability**:
- Owner:

**Comment by NicoDuvenage** [comment]
There has been some email correspondence regarding this topic lately, under the subject:

`Update regex in ML interfaces (API and outward facing services) to support accents (select Unicode characters) in names (#1261)`

**Comment by elnyry** [comment]
Not exactly on email, but on the GitHub issue here: https://github.com/mojaloop/project/issues/1261 (I suspect that email was just a GitHub notification)

**Comment by mjbrichards** [comment]
Just so we have it here too: here is my current thinking on what the specification should read, copied over from the GitHub issue:

_I think I'd like to suggest that there should be a reference somewhere in the API specification (preferably in a table of such versioning references) to the Unicode release level. Within that, we should use references to the Unicode General Categories that we allow or prohibit in a field of a specific type. So we might rewrite Miller's proposal to say:

"Letters, both accented and unaccented, being chosen from all code points belonging to the Letter and Decimal_Number general categories as defined in the reference version of the Unicode specification (with link to reference.) In addition, the period (.), apostrophe ('), dash (-), comma (,) and space character are permitted. Interior spaces are allowed, but no leading or trailing spaces. For the avoidance of doubt, Names may include leading digits."

We can then allow implementers to decide how best to meet these requirements._

My view is that, as Miller says elsewhere, it is much safer to use Unicode category names than to identify the content of those categories explicitly...

**Comment by mjbrichards** [comment]
Presumably the problem from a DA perspective is not the code solution, it's the tests we propose to apply to check whether a given solution meets the requirement or not...

**Comment by elnyry** [comment]
Here are the two issue tracking this for:

- Specification (FSPIOP API): https://github.com/mojaloop/mojaloop-specification/issues/56
- Implementation: https://github.com/mojaloop/project/issues/1261

**Comment by elnyry-sam-k** [comment]
All accented characters are now supported in implementation (example issue addressing this: https://github.com/mojaloop/project/issues/2358)
