### ISSUE TITLE
Deprecation of Helm2 support

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/design-authority-project#52]
## **Request**:

There are now mature tools for managing the migration of existing Helm deployments from Helm2 to Helm3 --> https://helm.sh/docs/topics/v2_v3_migration/.

As such we should consider deprecating Helm2 support going forward, and set a date a final date for switching over to only supporting Helm3 going forward.

Things that would be required to support this:
- update Mojaloop documentation on how to migrate from Helm2 to Helm3
- update existing deployment guides for Helm3 (they currently only support Helm2)
- identify communication channels to announce the pending, and final deprecation of Helm2

## **Rationale**:

- Helm2 is only being maintained for security issues and will be fully deprecated by Helm3 on [November 13, 2020](https://helm.sh/blog/covid-19-extending-helm-v2-bug-fixes/), with the final major release for helm2 being [2.15.0](https://helm.sh/blog/2019-10-22-helm-2150-released/)
- Helm2 is a security risk since it has access to the entire K8s environment due to its reliance on Tiller, Helm3 is more secure as it each helm installation is isolated to a specific namespace 

## **Impact**:

- Helm2 installations will need to be migrated to Helm3 using the [2to3 plugin](https://github.com/helm/helm-2to3).
- No impact to [existing Mojaloop Helm2 charts](https://github.com/mojaloop/helm) as they are supported by Helm3 - https://github.com/mojaloop/project/issues/1070
- However, In the future, this will allow us to fully upgrade existing helm2 charts to helm3 to take advantage of helm3's improved capabilities (ref: [1](https://github.com/helm/helm/issues/7109), [2](https://cloudblogs.microsoft.com/opensource/2019/11/13/helm-3-available-simpler-more-secure/), [3](https://blog.alcide.io/helm-3-released-bye-bye-tiller-and-why-secops-should-care))

**Artifacts**:
- https://helm.sh/docs/topics/v2_v3_migration/

**Decision(s)**:
- [ ] TBD

## **Follow-up**:
- [ ] Proposed Mojaloop documentation changes for Helm2 deprecation made for [#1283](https://github.com/mojaloop/project/issues/1283): https://github.com/mojaloop/documentation/p

**Dependencies**:
n/a

## **Accountability**:
- Owner: @mdebarros

**Comment by NicoDuvenage** [comment]
Closing this discussion with the migration document in place and an agreed approach of migrating over time, as there is backward compatibility in place and currently no urgent and immediate need.

**Comment by mdebarros** [comment]
@bushjames, I have closed this issue as I believe it was @NicoDuvenage's intent to do so.

Let me know otherwise.
