### ISSUE TITLE
Contingency Plan discussion (Generic) for Open-Source Library Support changes

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/design-authority-project#55]
## **Request**:
Consider a “Contingency plan in case an open source library’s support is in question”

**Artifacts**:
- [ ] Artifact to consider [@Contributor]

**Decision(s)**:
- [ ] Actual decision made as a result of discussion

## **Follow-up**:
- [ ] Alternative actions

**Dependencies**:
- [ ] If Applicable

## **Accountability**:
- Owner:

**Comment by godfreykutumela** [comment]
Hi, @elnyry-sam-k, can you please advise on the status of this issue? If it is not open for further discussion, I suggest moving it to closed or deferred.

**Comment by elnyry-sam-k** [comment]
@godfreykutumela - this is a tricky one, still relevant, Mojaloop still needs a plan for this or may be it can be on a case-by-case basis. I'll take this up in a few weeks time (close to end of Nov), thanks.. we can keep this deferred till then, if its ok.

**Comment by godfreykutumela** [comment]
Thanks, @elnyry-sam-k, for the feedback on this, and in that case, I suggest we move it to DA backlog instead.

**Comment by MichaelJBRichards** [comment]
This has been dealt with under the node dependencies decision. Close this issue.
