### ISSUE TITLE
Should the response to a GET /parties contain a correlation ID

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/design-authority-project#65]
## **Request**:
A request was made by Istvan to discuss the Correlation ID issue and how it has been implemented in the FSPIOP-API spec.
Michael brought a request to the DA forum to have an Ad-Hoc meeting titled:
"Should the response to a GET /parties contain a correlation ID"

**Artifacts**:
- [ ] Artifact to consider [@Contributor]

**Decision(s)**:
- [ ] Actual decision made as a result of discussion

## **Follow-up**:
- [ ] Alternative actions

**Dependencies**:
- [ ] If Applicable

## **Accountability**:
- Owner:

**Comment by NicoDuvenage** [comment]
The Ad-Hoc meeting was conducted with a wider issue being addressed relating to recommendations required to be taken to the CCB for consideration.

Many valid points were raised and discussed and Michael and Adrian suggested some collaboration on this platform to consolidate the ideas put forward in order to formulate a recommendation to the CCB.

**Comment by godfreykutumela** [comment]
Deferred to the CCB.

**Comment by MichaelJBRichards** [comment]
Close this issue. Raise with CCB.
