### ISSUE TITLE
Differentiate between "core" components and demos/POCs/etc

### ISSUE THREAD

**Issue by adrianhopebailie** [mojaloop/design-authority-project#67]
## **Request**:

As a follow up to #66 we need to find a way to avoid confusion in the market about what repos are part of the Mojaloop core and which are not.

https://docs.mojaloop.io/documentation/repositories/ provides a catalogue of repositories broken down into categories.

What this list doesn't show are tools or reference implementations of systems that would integrate with the Mojaloop core such as Fineract, the Mojaloop mobile app developed to show the PISP functionality, or the Web-based Mojawallet developed to demonstrate the ATM and POS integrations.

This list also provides no insight into who the maintainers are of the repositories so the assumption is that all repositories are maintained by the core OSS team.

To accept contributions that are not part of the core (or core dependencies) and/or will be maintained by the community (not the core team) we need to define:

 1. DONE see comments - A way to differentiate these repositories both in this list and on the repository README (maybe a badge or something?)
 2. EXTRACTED to a separate issue -  A process for accepting these kinds of projects into the Mojaloop organization and what the implications of that are (who maintains them etc) 

**Decision(s)**:
- [ ] Actual decision made as a result of discussion

## **Follow-up**:
- [ ] Alternative actions

**Dependencies**:
- [ ] If Applicable

## **Accountability**:
- Owner: @adrianhopebailie 

## **Notes**:

This discussion may need to include input from the TGB

**Comment by godfreykutumela** [comment]
Hi, @adrianhopebailie. What is the status of this DA issue? Is still open awaiting a decision, or can we mark it as deferred with comments?

**Comment by adrianhopebailie** [comment]
No, this is not yet resolved. We now have ATM and POS simulators and the test toolkit to add to this list of tools.

I suggest we get some guidance from Lesley-Ann on where these things should sit and how they should be managed.

**Comment by godfreykutumela** [comment]
Noted @adrianhopebailie, I will move this issue to the DA backlog to seek guidance from the Product Manager, as suggested.

**Comment by pedrosousabarreto** [comment]
We have a "Mojaloop GitHub repository management proposal" document that includes naming conventions for repositories, as well as a general strategy for repo management.

This doc resolves the first point of this issue. 

I believe the second one. regarding the process to accept contributions, should be separate.

https://docs.google.com/document/d/1AZbX0UjraytFty0IWOHpyR6z35bh0-MCFG1vGKId_5M/edit#heading=h.bc2swx7xaelr

**Comment by pedrosousabarreto** [comment]
Second point extracted to #86. Closing this one
