### ISSUE TITLE
Clarity on a few topics

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/design-authority-project#68]
## **Request**:
Here are a couple of discussion points we need clarity on:
1)  On quotes - no timeout mechanism is available on the Switch - is this ok?
2) The pattern for messaging specified in Mojaloop Specification  (FSPIOP API) in some cases doesn’t send error callbacks (for PUT calls) - thoughts?

**Artifacts**:
- [ ] Artifact to consider [@Contributor]

**Decision(s)**:
- [ ] Actual decision made as a result of discussion

## **Follow-up**:
- [ ] Alternative actions

**Dependencies**:
- [ ] If Applicable

## **Accountability**:
- Owner:

**Comment by NicoDuvenage** [comment]
Discussion around the topics mentioned started - the newly implemented "patch" in version 1.1 of the API spec was discussed and the majority of the meeting was spent on how to promote wider adoption of this new pattern. 

Concerns about the implementation and use of the "patch" command was raised, stating that further discussion is required to determine if we are not trying to patch a design flaw with another potential implementation flaw.

**Comment by elnyry-sam-k** [comment]
#2 above is now addressed by the usage of PATCH: https://github.com/mojaloop/mojaloop-specification/issues/103..

**Comment by elnyry-sam-k** [comment]
This issue can be refactored to address just the first issue in the description. The second issue has been addressed in the FSPIOP API
