### ISSUE TITLE
proposal: enforce conventional commit titles for Pull request reviews

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/design-authority-project#71]
## One Line Summary: 

In order to better automate our release lifecycle, we should adopt [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) in our GitHub pull request titles.

## **Request Details**:

- **Deadline:** This PI
- **Impact (Teams):** All teams working on open source codebases in the Mojaloop Github Org
- **Impact (Components):** All repos which build docker and npm targets, or any repo which we wish to automate the release of.

One of the goals of the versioning workstream in this PI is to adopt more automated release strategies for our repos. Automating releases reduces the operational burden on the community, makes it easier to write release notes, and can improve development workflows for others depending on our components.

[conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) has emerged as the industry standard for writing commit messages that can be used to automatically version software releases. We have adopted this approach with great success in some PISP workstream repos:
- https://github.com/mojaloop/thirdparty-api-adapter/releases
- https://github.com/mojaloop/thirdparty-scheme-adapter/releases

These releases and release notes were automatically generated based on the pull request titles, since the titles are what ends up being the merge commit message when github merges a PR.

We could add a PR title check similar to [this github action](https://github.com/marketplace/actions/conventional-pr-title) in CircleCI, which would perform the validation, and fail if the pull request title is not written correctly.

**Artifacts**:
### Example github action
- https://github.com/marketplace/actions/conventional-pr-title
### Examples of good release notes
- https://github.com/mojaloop/thirdparty-api-adapter/releases
- https://github.com/mojaloop/thirdparty-scheme-adapter/releases

**Dependencies**:
- [ ] Update the contributor's guide with how to write good commit messages, and information of breaking changes

### **Accountability**:
- **Owner:** @lewisdaly 
- **Raised By:** @lewisdaly 

## **Decision(s)**:

This was discussed on 9/12/20. The decision was made to adopt this proposal.

- **Approved By:** @godfreykutumela 
  
### Details

- [ ]  Update contributor's guide to mention the pr title formatting, how to specify a breaking change, and what constitutes a breaking change
- [x] Lewis to make a demo of using circleci to enforce this standard
- [ ] Once we are happy with the demo, apply to all 'core' repos

## **Follow-up**:

<fill in this section upon reaching a decision>
  
- [ ] PR for documentation updates: https://github.com/mojaloop/documentation/pull/297
- [ ] update ci/cd for all core repos

**Comment by godfreykutumela** [comment]
Noted @lewisdaly and this is scheduled for the first 10min of next week's session.

**Comment by elnyry-sam-k** [comment]
This looks good, @lewisdaly , thank you.. I think we should adopt this, now that we have adopted SemVer for about 1.5 PIs

**Comment by lewisdaly** [comment]
Here's an example implementation that works well with our CI/CD: https://github.com/mojaloop/ml-operator/blob/master/scripts/_pr_title.js

From here, I'll add it to our circleci orb to make it more manageable across many codebases.
