### ISSUE TITLE
IAC contribution to Mojaloop OSS

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/design-authority-project#72]
IAC contribution to Mojaloop OSS

**Comment by godfreykutumela** [comment]
Hi @elnyry-sam-k can you please add little bit more details to this?

**Comment by elnyry-sam-k** [comment]
All the IAC repos to be made public this week or next week (first week of June) as part of contribution from ModusBox which will work with the latest helm release v12.0.0
