### ISSUE TITLE
Design for reliable notifications on finalisation of a transfer

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/design-authority-project#74]
## Request Summary: 

Review/discussion for the `Design for reliable notifications on finalisation of a transfer` as per the following documentation: https://github.com/mojaloop/documentation/tree/feature/%231869Designforreliablenotificationsonfinalizationofatransfer/mojaloop-technical-overview/notifications

_(Please use the [PR](https://github.com/mojaloop/documentation/pull/288) to add any comments)_

**Story:** https://github.com/mojaloop/project/issues/1869

## **Request Details**:

- **Deadline:** 2021 Jan 15
- **Impact (Teams):** Core OSS
- **Impact (Components):** ML-API-Adapter - Notification Handler

**Artifacts**:
- [ ] **PR:** https://github.com/mojaloop/documentation/pull/288 (in draft)

**Dependencies**:
- n/a

### **Accountability**:
- **Owner:** @mdebarros
- **Raised By:** @mdebarros 

## **Decision(s)**:

<fill in this section upon reaching a decision>

- **Approved By:** <Insert name>
  
### Details

- [ ] Actual decision made as a result of discussion

## **Follow-up**:

<fill in this section upon reaching a decision>
  
- [ ] Actions to implement the decisions

**Comment by bushjames** [comment]
@mdebarros has updated defaults for image pull policy in all helm charts. Will be released with v12.0.0 of mojaloop. Monitor situation and review if issue persists.

**Comment by mdebarros** [comment]
Update 2022-01-03:
- DA agreed that there are no major pending issues with the proposal
- DA decision that this should be addressed as part of the vNext workstream
