### ISSUE TITLE
Produce Decision Log from DA Board History

### ISSUE THREAD

**Issue by bushjames** [mojaloop/design-authority-project#75]
## Request Summary: 

A project sponsor has requested that we create and maintain a design authority decision log. This can be facilitated by an analysis of the DA zenhub board.

## **Request Details**:

- **Deadline:** Next PI
- **Impact (Teams):** Design Authority
- **Impact (Components):** N/A

A decision log can be produced in some form e.g. Excel, text file, consensus post etc... (TBD) to record all issues considered by the DA since its inception. Most historic decisions should be captured in zenhub tickets so these will form a convenient starting point. We need to look back to see if there are any historical decisions before zenhub came into use and if they can also be captured.

**Artifacts**:
- [ ] DA Decision Log

**Dependencies**:
- [ ] N/A

### **Accountability**:
- **Owner:** DA Chair (@bushjames)
- **Raised By:** @millerabel 

## **Decision(s)**:

<fill in this section upon reaching a decision>

- **Approved By:** <Insert name>
  
### Details

- [ ] Actual decision made as a result of discussion

## **Follow-up**:

<fill in this section upon reaching a decision>
  
- [ ] Actions to implement the decisions

**Comment by elnyry-sam-k** [comment]
DA on 14th June: Considering the issues discussed on the DA are already captured in the form of issues here and comments made to capture discussions, the DA agreed to close this issue out.
