### ISSUE TITLE
Docker Hub rate limiting PULL requests

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/design-authority-project#76]
## Request Summary: 

The deployment of Mojaloop is severely impacted due to the recently imposed rate-limits on Docker-Hub Pull requests. The result being that deployment times have substantially increased.
 
Ref: https://www.docker.com/increase-rate-limits

## **Request Details**:

- **Deadline:** ASAP
- **Impact (Teams):** Core-OSS and Community
- **Impact (Components):** Mojaloop Helm Deployments

Agreement on how this can be best resolved. 

Current options:
1. Setup a local Proxy Cache service that pulls Docker images on behalf of the client, and caches the images locally. The images will then be served subsequently from the local cache thereby avoiding Docker-hub Pull requests and thus avoid rate-limiting. This option requires extra infrastructure and services to be installed and managed by the Core-OSS team.
2. Use a paid account (Docker Pro / Docker Team account) that provides unlimited Pull requests. This option requires the existing Docker org to be upgraded to a paid subscription, thereby removing the Pull request limits. In addition, there are some configurations changes required to Mojaloop Helm charts to support user authentication. 

**Artifacts**:
- n/a

**Dependencies**:
- [ ] https://github.com/mojaloop/project/issues/1968

### **Accountability**:
- **Owner:** @mdebarros
- **Raised By:** @mdebarros 

## **Decision(s)**:

<fill in this section upon reaching a decision>

- **Approved By:** <Insert name>
  
### Details

- [ ] Actual decision made as a result of discussion

## **Follow-up**:

<fill in this section upon reaching a decision>
  
- [ ] Actions to implement the decisions

**Comment by godfreykutumela** [comment]
Hi @mdebarros It looks like there is a cost associated with each of the two options proposed here so I recommend forwarding this as-is to Kim for guidance.

**Comment by lewisdaly** [comment]
@mdebarros yeah I've noticed this when deploying as well... it's a real pain.

With option #2, does that mean that users wishing to use our charts are still rate limited? My concern is newcomers to the community struggling to get up and running with our helm charts, and I think we need to consider that in any solution.

**Comment by lewisdaly** [comment]
This link has some helpful tips: https://blog.container-solutions.com/dealing-with-docker-hub-rate-limiting

**Comment by bushjames** [comment]
Presented and discussed at DA meeting 2021-01-20 13:00 UTC

**Comment by mdebarros** [comment]
Updates to v11.1.0 Helm release:
- Update Docker pull policies to "IfNotPresent", this will help with the Docker rate-limiting changes as described in this issue to both the wider community and OSS team.

**Comment by bushjames** [comment]
@mdebarros has updated default image pull policy on helm charts. Will be released as part of v12.0.0 mojaloop. Monitor situation and revisit if issue persists.

**Comment by elnyry-sam-k** [comment]
helm v12.0.0 : https://github.com/mojaloop/helm/releases/tag/v12.0.0 released last week (Feb 15th)
