### ISSUE TITLE
Grafana changing license to AGPL 3

### ISSUE THREAD

**Issue by adrianhopebailie** [mojaloop/design-authority-project#77]
## Request Summary: 

Analyse impact of the license change that Grafana have made from Apache 2.0 to AGPL

## **Request Details**:

- **Deadline:** End of the current PI
- **Impact (Teams):** Any teams depending on Grafana as part of their work
- **Impact (Components):** Grafana

Grafana Labs have changed the license for Grafana from Apache 2.0 to AGPL:
https://grafana.com/blog/2021/04/20/grafana-loki-tempo-relicensing-to-agplv3/

This license is not compatible with the Mojaloop licensing requirements for dependencies.

### **Accountability**:
- **Owner:** <DA member responsible for issue>
- **Raised By:** @adrianhopebailie 

## **Decision(s)**:

<fill in this section upon reaching a decision>

- **Approved By:** <Insert name>
  
### Details

- [ ] Actual decision made as a result of discussion

## **Follow-up**:

<fill in this section upon reaching a decision>
  
- [ ] Actions to implement the decisions

**Comment by mdebarros** [comment]
https://grafana.com/blog/2021/04/20/qa-with-our-ceo-on-relicensing/

I am of the opinion that the license change will not impact our usage of Grafana. I believe it will only be an issue if we modify Grafan’s code, which will trigger the “network” part of the **A**GPL license.

**Comment by godfreykutumela** [comment]
I agree with @mdebarros. There are 3 conditions on which this can impact us:

1. If you provide a competing service to Grafana - Grafana as a service to our customers
2. If we modify the source code of Grafana and if we do it only affect the part we changed not the entire code but anyway our code is public.
3. If we provide a Gradana based solution as a public service via a public cloud or private.

In our case, we are using Grafana as an internal system so it is fully allowed as per AGPL conditions.

**Comment by ehenrka** [comment]
I would recommend to have someone with more legal expertise in the area of software licenses to have a look at this. Modification can be interpreted in different ways, see for example https://opensource.stackexchange.com/a/6904, but this depends on how strict Grafana Labs wants to be.

Also, based on https://www.gnu.org/licenses/gpl-faq.html#IfLibraryIsGPL, would not the license of Mojaloop have to be changed to a GPL license as it would use the GPLed library? See also excerpt from https://www.apache.org/licenses/GPL-compatibility.html:

> However, GPLv3 software cannot be included in Apache projects. The licenses are incompatible in one direction only, and it is a result of ASF's licensing philosophy and the GPLv3 authors' interpretation of copyright law.

**Comment by ehenrka** [comment]
Additionally regarding the license incompatibility, see excerpt from https://github.com/mojaloop/mojaloop/blob/master/contribute/License.md:

> Mojaloop code is created with the intention that it could be released using an Apache 2.0. To make this possible, all dependent libraries and tools must have a license that conforms to Apache 2.0. Submissions that do not meet this will be rejected.

**Comment by millerabel** [comment]
Thanks Henrik for providing the excerpts. When we organized the open source project, we identified this incompatibility between Apache 2.0 and the GPL family of licenses and so the use of GPL’d libraries in Mojaloop contributions is not permitted. As these libraries are sometimes imported at a very deep dependency, within our module tree, it has been a constant challenge to find and remove the dependencies. And, when a major platform switches license to a GPL family license, we must switch to something else or we place the project in jeopardy. We established the no-GPL principle to protect the commercial uses of the platform and to remove uncertainty for adopters.

— Miller

Miller Abel
***@***.***



On Apr 28, 2021, at 2:27 AM, Henrik Karlsson ***@***.***> wrote:


Additionally regarding the license incompatibility, see excerpt from https://github.com/mojaloop/mojaloop/blob/master/contribute/License.md <https://github.com/mojaloop/mojaloop/blob/master/contribute/License.md>:

Mojaloop code is created with the intention that it could be released using an Apache 2.0. To make this possible, all dependent libraries and tools must have a license that conforms to Apache 2.0. Submissions that do not meet this will be rejected.

**Comment by ehenrka** [comment]
Thanks Miller, that is consistent with my view from commercial usage.

A related potential issue with the current license in https://github.com/mojaloop/mojaloop/blob/master/contribute/License.md is for Elasticsearch and Kibana. These are, starting from version 7.11, dual licensed under the Elastic License and Server Side Public License instead of Apache 2.0. As far as I know, Mojaloop is in some way using both Elasticsearch and Kibana in some way. Maybe this has already been discussed elsewhere..

**Comment by mdebarros** [comment]
> I would recommend to have someone with more legal expertise in the area of software licenses to have a look at this. Modification can be interpreted in different ways, see for example https://opensource.stackexchange.com/a/6904, but this depends on how strict Grafana Labs wants to be.
> 
> Also, based on https://www.gnu.org/licenses/gpl-faq.html#IfLibraryIsGPL, would not the license of Mojaloop have to be changed to a GPL license as it would use the GPLed library? See also excerpt from https://www.apache.org/licenses/GPL-compatibility.html:
> 
> > However, GPLv3 software cannot be included in Apache projects. The licenses are incompatible in one direction only, and it is a result of ASF's licensing philosophy and the GPLv3 authors' interpretation of copyright law.

We are not using any library for Grafana as we do not directly integrate with Grafana.

Grafana integrates into Prometheus by providing visualization dashboards.  However, we use the following client library to expose metrics (which are scrapped by Prometheus) --> https://github.com/siimon/prom-client. This client licensed under Apache 2.0. License.

**Comment by millerabel** [comment]
Okay, this is excellent. Thanks Miguel for exploring the connections. Indeed, AGPL inherits the GPL's “viral on modification” and “viral on linking” philosophy, and it adds restrictions on service hosting of the stack. This is (according the AGPL authors) an attempt to prevent AWS and Azure from “free riding” by offering paid services powered by open source projects, without sharing revenue with the open source projects. It was created to protect the enterprise/community split that a lot of companies use to offer paid services into market that build beyond the community editions of their stacks.

So, under AGPL, we can’t host the “Grafana stack” for use by others. And if what we build requires the use of the Grafana stack, we must investigate how we link to it (that is, how it’s incorporated into Mojaloop images), and how it would be used by others, particularly in a hosted SaaS context. Ask the question, “if ACME Cloud Corporation hosted Mojaloop, and charged a fee to utilize it, would that be disallowed by the Grafana component license?” And what would the alternative be for a commercial company wanting to offer metrics and visualization?

Is our connection to Prometheus (and so its use of Grafana) permitted under the Apache 2.0 and the inbound licenses used by Prometheus and its dependencies?

If a hosting service provider chose to use something else, do we have clean interfaces (e.g. Open Trace, etc…) that would allow them to replace the Prometheus stack and components?

If we can explain the relationship between Grafana (and the other Elastic components that we depend on, as they are all changing license) and Mojaloop, we can ask the board to provide legal support to help us iterate to a solution.

— Miller

Miller Abel
***@***.***



On May 12, 2021, at 3:47 AM, Miguel de Barros ***@***.***> wrote:


I would recommend to have someone with more legal expertise in the area of software licenses to have a look at this. Modification can be interpreted in different ways, see for example https://opensource.stackexchange.com/a/6904 <https://opensource.stackexchange.com/a/6904>, but this depends on how strict Grafana Labs wants to be.

Also, based on https://www.gnu.org/licenses/gpl-faq.html#IfLibraryIsGPL <https://www.gnu.org/licenses/gpl-faq.html#IfLibraryIsGPL>, would not the license of Mojaloop have to be changed to a GPL license as it would use the GPLed library? See also excerpt from https://www.apache.org/licenses/GPL-compatibility.html <https://www.apache.org/licenses/GPL-compatibility.html>:

However, GPLv3 software cannot be included in Apache projects. The licenses are incompatible in one direction only, and it is a result of ASF's licensing philosophy and the GPLv3 authors' interpretation of copyright law.

We are not using any library for Grafana as we do not directly integrate with Grafana.

Grafana integrates into Prometheus by providing visualization dashboards. However, we use the following client library to expose metrics (which are scrapped by Prometheus) --> https://github.com/siimon/prom-client <https://github.com/siimon/prom-client>. This client licensed under Apache 2.0. License.
