### ISSUE TITLE
Upgrading node version to the latest LTS (v16.x.x)

### ISSUE THREAD

**Issue by elnyry-sam-k** [mojaloop/design-authority-project#78]
## Request Summary: 

Upgrade Mojaloop (core & supporting) services to Node version v14.x.x (from v12.x.x)

## **Request Details**:

- **Deadline:** 2 weeks (by end of May - decision)
- **Impact (Teams):** All dev teams
- **Impact (Components):** All core and supporting services to be upgraded so will be impacted in some way

<insert more information about your request>

**Artifacts**:
- [ ] Artifact to consider [@Contributor]

**Dependencies**:
- [ ] If Applicable

### **Accountability**:
- **Owner:** Core team (Sam, Miguel, Valentin, Vijay)
- **Raised By:** Adrian, DA

## **Decision(s)**:

TBD

- **Approved By:** DA (attendees on 26th May 2021)
  
### Details

- [ ] Helm v12.1.0 to proceed with current version of node (no upgrade)
- [ ] After helm release done, when fixing or touching any service, upgrade node version to v14.x.x (v14.17.0), the latest LTS and assess impact
- [ ] If straight forward, continue with upgrading rest of services, else propose that this upgrade be done as part of Ref.Arch workstream (developing the vNext of ML core)

## **Follow-up**:

<fill in this section upon reaching a decision>
  
- [ ] Actions to implement the decisions

**Comment by elnyry-sam-k** [comment]
Discussed on May 19th initially: Sam K agreed to take it up and discuss with core team to assess impact and next steps and report back to the DA.

May 26th 2021: Discussed on the DA call and made the below proposal

- Since node v12 LTS support ends only in April 2022, we'll continue with helm v12.1.0 with node v12 
- After the helm release, as part of maintenance, as we touch a core service, we'll upgrade it to v14 LTS version and reassess the situation
- If straight forward, continue with upgrading rest of services
- else propose that this upgrade be done as part of Ref.Arch work-stream (developing the vNext of ML core), since thats a huge refactoring anyway
- Need to set a reminder around October timeframe to remind adopters / implementers to ensure everyone is upgraded to latest versions of services (and that the services themselves are upgraded) that use v14 LTS

**Comment by mdebarros** [comment]
I believe we should update this issue to upgrade Node v12.x to the latest current supported version - which is currently v17.x (released 2021-10-19).

Reference: https://nodejs.org/en/about/releases/

**Comment by elnyry-sam-k** [comment]
Link to the Epic on project repo for tracking: https://github.com/mojaloop/project/issues/2092 

This epic contains all the stories part of this effort..

**Comment by lewisdaly** [comment]
We're just waiting for this [documentation issue](https://github.com/mojaloop/project/issues/2743) to be done before we consider this complete.

**Comment by mdebarros** [comment]
> We're just waiting for this [documentation issue](https://github.com/mojaloop/project/issues/2743) to be done before we consider this complete.

PR created for documentation to include outcome of this DA issue: https://github.com/mojaloop/documentation/pull/379 (note this PR includes additional maintenance updates)

**Comment by elnyry-sam-k** [comment]
Can be closed with: https://github.com/mojaloop/documentation/pull/379 according to final discussions on this
