### ISSUE TITLE
Payment Manager Adoption

### ISSUE THREAD

**Issue by lewisdaly** [mojaloop/design-authority-project#85]
## Request Summary: 

Mojaloop Community adoption of Payment Manager

## **Request Details**:

- **Deadline:** <When do we need a decision by?>
- **Impact (Teams):** <If your proposal is accepted, what team(s) will be affected by it?>
- **Impact (Components):** Mojaloop SDK, 

DA TODOs:
- [ ] review the documentation (all)
- [ ] review docs related to constructing new Connectors (from hackathon participant's perspective @MichaelJBRichards)
- [x] conduct a OSS Scan on dependency vulnerabilities, libraries (@lewisdaly, @godfreykutumela )
- [ ] detailed code review (@lewisdaly, @pedrosousabarreto )
- [ ] Run the docker-compose version: https://github.com/pm4ml/on-premise-deploy

Issues raised by the DA to be addressed by Payment Manager Team
- [ ] Repository naming conventions - concern about adding 25 new repos to the Mojaloop org
- [ ] Fork of the Mojaloop SDK must be merged in before Payment Manager can be adopted
- [ ] E2E tests - how are they run? What is their scope? Are they automated?

Post-Adoption Followup
- [ ] Unit test coverage for individual repos

**Artifacts**:
- [ ] Payment Manager github org: https://github.com/pm4ml/
- [ ] Docs: https://pm4ml.github.io/documents/payment_manager_oss/latest/index.html

**Dependencies**:
- [ ] If Applicable

### **Accountability**:
- **Owner:** @lewisdaly 
- **Raised By:** @lewisdaly 

## **Decision(s)**:

<fill in this section upon reaching a decision>

- **Approved By:** <Insert name>
  
### Details

- [ ] Actual decision made as a result of discussion

## **Follow-up**:

<fill in this section upon reaching a decision>
  
- [ ] Actions to implement the decisions

**Comment by godfreykutumela** [comment]
What is the status of this issue! @lewisdaly @MichaelJBRichards
