### ISSUE TITLE
CircleCI configurations requires maintenance for deprecated Ubuntu versions

### ISSUE THREAD

**Issue by mdebarros** [mojaloop/design-authority-project#87]
## Request Summary: 

Some of our CircleCI Jobs (core & supporting) are running on deprecated versions of Ubuntu:

```
This job is either using an Ubuntu 14.04 image, an Ubuntu 16.04 image, or the default Ubuntu 14.04-based image by specifying machine:true in config. These images (including the default image) will be deprecated May 31, 2022. Upgrade your image from Ubuntu 14.04 or 16.04 to 20.04.
```

## **Request Details**:

- **Deadline:** TBD
- **Impact (Teams):** All dev teams
- **Impact (Components):** Potentially all components that rely on CircleCI

<insert more information about your request>

**Artifacts**:
- [ ] Artifact to consider [@Contributor]

**Dependencies**:
- [ ] If Applicable

### **Accountability**:
- **Owner:** Core team?
- **Raised By:** @mdebarros , DA

## **Decision(s)**:

TBD

- **Approved By:** DA (attendees on 26th May 2021)
  
### Details

- [ ] Many CircleCI configurations that are part of our Core-Components and supporting services are using Ubuntu v14.x and v16.x images to execute CI job (i.e. docker builds, npm tests, etc) which will be deprecated on May 31, 2022
- [ ] Discussion on CircleCI configurations maintenance required to support Ubuntu v20.x (or newer) 

## **Follow-up**:

<fill in this section upon reaching a decision>
  
- [ ] Actions to implement the decisions

**Comment by bushjames** [comment]
Closing. This was resolved long time ago but ticket not updated.
