### ISSUE TITLE
Approach for storing Invalid Requests for Prepare/Fulfils

### ISSUE THREAD

**Issue by NicoDuvenage** [mojaloop/design-authority-project#9]
## **Request**:
Current functional logic of the saveTransferPrepared facade is implemented so that a try-catch block wraps the entire logical insertion of the transfer, transferParticipant, transferExtension, ilpPacket, & transferStateChange. If any of those inserts fail, the catch will roll back the entire transfer. E.g. if the participant doesn't exist, the insertion into the transferParticipant table cause an error to be thrown thereby causing a complete roll-back.

The outcome being that no record is stored, and a new transferId can be retried. 

**Artifacts**:
- [x] Artifact to consider [@Contributor]

**Decision(s)**:
- [x] Actual decision made as a result of discussion

## **Follow-up**:
- [ ] Alternative actions

**Dependencies**:
- [ ] If Applicable

## **Accountability**:
- Owner: 

## **Notes**:

**Comment by mdebarros** [comment]
This is being addressed by the following story: https://github.com/mojaloop/project/issues/780. The design proposal will be submitted by @ggrg.

**Comment by mdebarros** [comment]
See decision made as part of https://github.com/mojaloop/design-authority/issues/29 as option 4 was selected which resolves this issue.
