### ISSUE TITLE
Change the basis for the liquidity check

### ISSUE THREAD

**Issue by mjbrichards** [mojaloop/design-authority-project#90]
## Request Summary: 

Make the liquidity check a comparison between the position account and the settled funds account as modified by the NDC, instead of between the position account and the NDC.

## **Request Details**:

- **Deadline:** Resource is available to make this change quickly, if approved.
- **Impact (Teams):** Core components team
- **Impact (Components):** Transfer prepare

At present, the liquidity check performed as part of transfer preparation compares the position account (plus the amount of the proposed transfer) against the NDC. If a participant makes changes to their settled funds via deposit and withdrawal, then the NDC needs to be adjusted as well before the change can be effective in the liquidity cover calculation.

The proposal is to use the settlement account (for the settlement model in operation) instead of the NDC as the funds available to cover transactions in the system, and to reserve the NDC as a way of inflecting the funds available for liquidity cover: for instance, if a participant is a net creditor in the system but wishes to protect itself against fraudulent withdrawals, it can specify that only a given amount of its settled funds may be used for liquidity cover.

The proposed form of the liquidity check will be: if the net of the position account and (the settlement account as inflected by the NDC) is greater than the amount of the proposed transfer, then the transfer request will be accepted; if not, it will be rejected.

**Artifacts**:
- [ ] Artifact to consider [@Contributor]

**Dependencies**:
- [ ] If Applicable

### **Accountability**:
- **Owner:** Paul Baker
- **Raised By:** Michael Richards

## **Decision(s)**:

<fill in this section upon reaching a decision>

- **Approved By:** <Insert name>
  
### Details

- [ ] Actual decision made as a result of discussion

## **Follow-up**:

<fill in this section upon reaching a decision>
  
- [ ] Actions to implement the decisions

**Comment by mdebarros** [comment]
Approved 2022-04-20 by DA.
