### ISSUE TITLE
mojaloop deployment status and issues 

### ISSUE THREAD

**Issue by tdaly61** [mojaloop/design-authority-project#91]
## Request Summary: 
 The 13.x release of Mojaloop does not deploy to current kubernetes releases and this is starting to cause a significant amount of challenge for those trying to deploy it 

Seeking to raise awareness of scope and significance of the issues and to get agreement on a solution
## **Request Details**:

- **Deadline:** <When do we need a decision by?>
- ASAP
- **Impact (Teams):** <If your proposal is accepted, what team(s) will be affected by it?>
- core team for changes 
- all teams for results 
- **Impact (Components):** <If your proposal is accepted, which components (e.g. APIs, docs, codebases) will be affected by it?>
- helm charts 

<insert more information about your request>
it is all in the slides linked above 

**Artifacts**:
- [x ] Artifact to consider [@Contributor] https://docs.google.com/presentation/d/1YkbhepkGrZfObOYuOwsBlzKysAy2BzhESVGHYYxPfxw/edit?usp=sharing
- 

[**Dependencies**:]()))
- [ ] If Applicable

### **Accountability**:
- **Owner:** <DA member responsible for issue>
- **Raised By:** @tdaly61 

## **Decision(s)**:

<fill in this section upon reaching a decision>

- **Approved By:** <Insert name>
  
### Details

- [ ] Actual decision made as a result of discussion

## **Follow-up**:

<fill in this section upon reaching a decision>
  
- [ ] Actions to implement the decisions please see linked slide set

**Comment by lewisdaly** [comment]
## Decision to be made:
1. Either update Percona to something modern (breaking)
2. Remove chart dependencies and issue a breaking change
3. Do nothing, wait for new refactored charts
4. Just make the ingress change (non-breaking) and flip the default to not deploy percona by default

**Comment by mdebarros** [comment]
> ## Decision to be made:
> 1. Either update Percona to something modern (breaking)
> 2. Remove chart dependencies and issue a breaking change
> 3. Do nothing, wait for new refactored charts
> 4. Just make the ingress change (non-breaking) and flip the default to not deploy percona by default

On point 4 option. We could introduce another `percona` alternative that is enabled by default but still maintain `percona` as an option which is disabled by default for "backward" compatibility. However, this would necessarily help anyone that is upgrading from K8s v1.21 to v1.22.

**Comment by lewisdaly** [comment]
Agreed to:

- From Monday 26th, @tdaly61 will start modifying the current helm chart to:
    - Swap out databases from `percona` to `bitnami/mysql`
    - Update ingress annotations
    - Investigate and (maybe) fix PodDisruption budgets
    - Move Kafka and MongoDB dependencies to external chart (already done in next charts, but not in current)

**Comment by MichaelJBRichards** [comment]
Close this: work has been done
